apiVersion: v1
kind: ConfigMap
metadata:
  name: smarthire-config
  namespace: smarthire
data:
  NEXT_PUBLIC_BASE_URL: http://smarthire.local
  BASE_API_URL: http://smarthire.local/api/api
  INTERVIEW_API: http://smarthire.local/api/interview
  NEXTAUTH_URL: http://smarthire.local