"""Add InterviewSession model

Revision ID: 0753a5dc9f01
Revises: 7698958756ee
Create Date: 2025-12-07 07:16:43.443985

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0753a5dc9f01'
down_revision = '7698958756ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_session',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('strengths', sa.Text(), nullable=True),
    sa.Column('weaknesses', sa.Text(), nullable=True),
    sa.Column('suggestions', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_session')
    # ### end Alembic commands ###
