"""Added input_format and output_format to coding_question

Revision ID: 7698958756ee
Revises: fa13295107ff
Create Date: 2025-12-06 23:09:35.525112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7698958756ee'
down_revision = 'fa13295107ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('input_format', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('output_format', sa.Text(), nullable=True))
        batch_op.drop_column('function_signature')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coding_question', schema=None) as batch_op:
        batch_op.add_column(sa.Column('function_signature', sa.VARCHAR(length=300), autoincrement=False, nullable=False))
        batch_op.drop_column('output_format')
        batch_op.drop_column('input_format')

    # ### end Alembic commands ###
